# Generated by Django 4.1.4 on 2023-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('image', models.ImageField(upload_to='roadsafety/')),
            ],
        ),
    ]
