# Generated by Django 4.1.4 on 2023-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsafety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsafety',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadsafety/'),
        ),
    ]
